# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "subscriber-proxy.fullname" . }}-targetconfig
  labels:
    app: {{ template "subscriber-proxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{ $root := . }}
  {{ range $path, $bytes := .Files.Glob "files/configs/*.json" }}
  {{ base $path }}: '{{ $root.Files.Get $path }}'
  {{ end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "subscriber-proxy.fullname" . }}-logconfig
  labels:
    app: {{ template "subscriber-proxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  logging.yaml: |-
{{ toYaml .Values.logging | indent 4 }}
