# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "e2-simulator.fullname" . }}
  labels:
    {{- include "e2-simulator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "e2-simulator.fullname" . }}
      app: onos
      type: e2-simulator
      resource: {{ template "e2-simulator.fullname" . }}
      {{- include "e2-simulator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ template "e2-simulator.fullname" . }}
        app: onos
        type: e2-simulator
        resource: {{ template "e2-simulator.fullname" . }}
        {{- include "e2-simulator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "e2-simulator.imagename" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /home/e2sim/build/e2sim
            - "${E2_SERVICE:-onos-e2t}"
            - "${E2SIM_PORT:-36421}"
          env:
            - name: E2_SERVICE
              value: {{ .Values.service.name | default "onos-e2t" }}
            - name: E2_PORT
              value: {{ .Values.service.port | default 36421 | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
